### ISSUE TITLE
How to make it work in the browser

### ISSUE THREAD

**Issue by xiaoran-MENG** [ankit1329/Eml-Parser#20]
I am trying to bring it in an HTML file as CDN to work in the **browser** and get the attachements out of an **uploaded** .eml file.
But there are `require` statements in the the Eml Parser code that prevent it to work from the browser
I tried a few bundlers, but they still contain the `require` statements
Do you have any suggestions on how to do it ?

**Comment by ankit1329** [comment]
@xiaoran-MENG  this uses nodejs streams so it won't work in browser, you are free to look at the code and copy the implementation for eml and msg after loading the file in browser however u like.
