### ISSUE TITLE
getEmailAsHtml() => Cannot read property 'html' of undefined 

### ISSUE THREAD

**Issue by QuentinChaumont** [ankit1329/Eml-Parser#8]
Hi,

First thank your for your tool.

_Error recorded_
We trigger an exception using `EmlParser(readable).getEmailAsHtml()`, the exception : `Cannot read property 'html' of undefined at /home/node/app/node_modules/eml-parser/index.js:87:50`.

_Context_
The email corresponding to the eml was sent without destination (to) only carbon copy (cc). I didn't know this was possible but i succeed to send one like that.

_Solution :_
 The fix look quite simple : just add a condition wrapping the "To : " statement in the html template like you did for cc.
 
 Thanks for your time.

**Comment by ankit1329** [comment]
Hi @QuentinChaumont ,
I've pushed this fix in 1.0.7.
Thanks for using this project and reporting the issue 😃

**Comment by QuentinChaumont** [comment]
Thank you for your time.
We'll update to last version.
