### ISSUE TITLE
Exposing Config options?

### ISSUE THREAD

**Issue by torsorensen** [ankit1329/Eml-Parser#9]
Hi, thanks very much for providing this project to the public.

We found the following config in your source, which is sent to html-pdf.

```
 let options = {
    orientation: 'landscape'
};
```
We were looking for a way to adapt it, but now a question popped up:
Is there a reason why you hardcoded it to landscape and not exposing it as a config option to users of this library?

Thanks in advance!

**Comment by ankit1329** [comment]
Hi @torsorensen,
Thanks for using this project. I've exposed the orientation and format options in 1.0.7.
This started out as a utility for a lot of our internal projects, later we casually decided to publish it. For the same reason, I never really thought of making it very configurable and also can't invest much time in this project.
Any PR will be greatly appreciated.😃
However I do try to fix any issues as soon as I notice it.
